branch-defaults:
  main:
    environment: Pocpythonmongo-env-1
environment-defaults:
  Pocpythonmongo-env-1:
    branch: null
    repository: null
global:
  application_name: poc-python-mongo
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
